[railway]
  plugin = "nodejs"

[build]
  builder = "NIXPACKS"

[deploy]
  startCommand = "cp -r database server/ && cd server && sed -i 's/const schema = fs.readFileSync/schema = fs.readFileSync/g' src/db/init.js && npm install && node src/db/init.js && node src/server.js"
  restartPolicyType = "ON_FAILURE"
  restartPolicyCount = 3
