[railway]
  plugin = "nodejs"

[build]
  builder = "NIXPACKS"

[deploy]
  startCommand = "cp -r database server/ && cd server && npm install && node src/db/init.js && node src/server.js"
  restartPolicyType = "ON_FAILURE"
  restartPolicyCount = 3
